# Generated by Django 2.1.7 on 2019-02-15 10:34

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, verbose_name='_Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'permissions': (('change_between_departments', 'Can change between Departments'),),
            },
        ),
        migrations.CreateModel(
            name='OwnerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Owner group',
                'verbose_name_plural': 'Owner groups',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar')),
                ('is_owner_admin', models.BooleanField(default=False)),
                ('email_is_verified', models.BooleanField(default=False, editable=False)),
                ('forbidden_counter', models.PositiveIntegerField(blank=True, default=0, editable=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Department')),
                ('group', models.ManyToManyField(blank=True, to='members.OwnerGroup')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddField(
            model_name='ownergroup',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownergroup_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownergroup',
            name='permission',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__in': ['add_userprofile', 'delete_userprofile', 'view_userprofile', 'change_userprofile', 'change_between_departments', 'add_department', 'change_department', 'view_department', 'delete_department', 'add_ownergroup', 'change_ownergroup', 'view_ownergroup', 'delete_ownergroup']}, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='ownergroup',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=common.models.SET_OWNER, related_name='ownergroup_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ManyToManyField(blank=True, to='members.OwnerGroup'),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=common.models.SET_OWNER, related_name='department_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
